# app/Dockerfile

FROM python:3.10-bookworm as backend

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     software-properties-common \
#     curl \
#     && pip install --upgrade pip \
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /app
VOLUME /user_files

COPY requirements.txt requirements.txt
COPY chatbot-backend-docker-init.sh /usr/local/bin/chatbot-backend-docker-init.sh

RUN pip install -r requirements.txt

ENV CHATBOT_ENV=api
ENV FLASK_APP=project
ENV FLASK_RUN_PORT=8502
ENV FLASK_ENV=production
ENV FLASK_DEBUG=0
ENV NEXT_TELEMETRY_DISABLED=1
ENV ANONYMIZED_TELEMETRY=False
ENV FILES_DIR=/user_files

EXPOSE 8502 8503 8504

ENTRYPOINT chatbot-backend-docker-init.sh
