# app/Dockerfile

FROM python:3.10-bookworm as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    curl \
    git \
    supervisor \
    && pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
VOLUME /user_files

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

ENV FLASK_APP=project
ENV FLASK_RUN_PORT=8502
ENV FLASK_ENV=production
ENV FLASK_DEBUG=0
ENV NEXT_TELEMETRY_DISABLED=1
ENV ANONYMIZED_TELEMETRY=False
ENV FILES_DIR=/user_files

EXPOSE 8502 8503 8504

# API
ENTRYPOINT ["flask", "run", "--port=8502", "--host=0.0.0.0"]
# Worker
# ENTRYPOINT ["celery", "-A", "make_celery", "worker", "-l", "info", "-E"]
# Flower
# ENTRYPOINT ["celery", "flower", "--address=0.0.0.0","-A", "make_celery", "--port=8504"]
# Socketio
# ENTRYPOINT ["gunicorn", "--workers=1", "--worker-class=eventlet",  "--bind=0.0.0.0:8503", "wsgi:app"]
# Scheduler
# ENTRYPOINT ["celery", "-A", "make_celery", "beat", "-l", "info"]

FROM builder as backend