name: Build Chatbot Image

concurrency:
  group: Build Chatbot Image
  cancel-in-progress: true

on:
  workflow_dispatch:

env:
  DOCKER_USER: foxsystem
  PLATFORMS: linux/amd64, linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Setup
        uses: docker/setup-buildx-action@v3

      - name: Build Api Dev
        uses: docker/build-push-action@v3
        with:
          context: ./chatbot
          platforms: ${{ env.PLATFORMS }}
          file: ./chatbot/dockerfile
          push: true
          target: api_dev
          tags: ${{ env.DOCKER_USER }}/chatbot-api:dev

      - name: Build Api
        uses: docker/build-push-action@v3
        with:
          context: ./chatbot
          platforms: ${{ env.PLATFORMS }}
          file: ./chatbot/dockerfile
          push: true
          target: api
          tags: ${{ env.DOCKER_USER }}/chatbot-api:latest

      - name: Build Worker
        uses: docker/build-push-action@v3
        with:
          context: ./chatbot
          platforms: ${{ env.PLATFORMS }}
          file: ./chatbot/dockerfile
          push: true
          target: worker
          tags: ${{ env.DOCKER_USER }}/chatbot-worker:latest

      - name: Build Scheduler
        uses: docker/build-push-action@v3
        with:
          context: ./chatbot
          platforms: ${{ env.PLATFORMS }}
          file: ./chatbot/dockerfile
          push: true
          target: scheduler
          tags: ${{ env.DOCKER_USER }}/chatbot-scheduler:latest

      - name: Build SocketIO
        uses: docker/build-push-action@v3
        with:
          context: ./chatbot
          platforms: ${{ env.PLATFORMS }}
          file: ./chatbot/dockerfile
          push: true
          target: socketio
          tags: ${{ env.DOCKER_USER }}/chatbot-socketio:latest
