name: Build Chatbot Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: build tags
        type: choice
        options:
          - develop
          - latest
        required: true
        default: develop

env:
  DOCKER_USER: foxsystem
  PLATFORMS: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Setup
        uses: docker/setup-buildx-action@v3

      - name: Build Chatbot Api
        uses: docker/build-push-action@v3
        with:
          context: ./chatbot
          platforms: ${{ env.PLATFORMS }}
          file: ./chatbot/dockerfile
          push: true
          target: api
          tags: ${{ env.DOCKER_USER }}/chatbot-api:latest
